CAP_PROP_FRAME_WIDTH: 3
CAP_PROP_FRAME_HEIGHT: 4
CAP_PROP_FPS: 5
SET_NAME: 'drone_classes'
VID_REGEX: '*DJI*'
VIDEO_SUFFIX: '*.MP4'
IMG_SUFFIX: '.jpg'
OUTPUT__SUFFIX: '.mp4'
OUTPUT_GT_SUFFIX: '_gt.mp4'
